; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\workspaces\newagent2\runtime.tools\src\ibmras\common\util\sysUtils.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	__$ArrayPad$
PUBLIC	?getMilliseconds@util@common@ibmras@@YA_KXZ	; ibmras::common::util::getMilliseconds
EXTRN	__imp__GetSystemTime@4:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__allmul:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_millisecondsSinceEpoch$ = -32				; size = 8
_st$ = -20						; size = 16
__$ArrayPad$ = -4					; size = 4
?getMilliseconds@util@common@ibmras@@YA_KXZ PROC	; ibmras::common::util::getMilliseconds
; File c:\workspaces\newagent2\runtime.tools\src\ibmras\common\util\sysutils.cpp
; Line 35
	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	esi
; Line 40
	lea	eax, DWORD PTR _st$[ebp]
	push	eax
	call	DWORD PTR __imp__GetSystemTime@4
; Line 42
	push	0
	call	_time
	add	esp, 4
	push	0
	push	1000					; 000003e8H
	push	edx
	push	eax
	call	__allmul
	mov	ecx, eax
	mov	esi, edx
	movzx	eax, WORD PTR _st$[ebp+14]
	cdq
	add	ecx, eax
	adc	esi, edx
	mov	DWORD PTR _millisecondsSinceEpoch$[ebp], ecx
	mov	DWORD PTR _millisecondsSinceEpoch$[ebp+4], esi
; Line 52
	mov	eax, DWORD PTR _millisecondsSinceEpoch$[ebp]
	mov	edx, DWORD PTR _millisecondsSinceEpoch$[ebp+4]
; Line 53
	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
?getMilliseconds@util@common@ibmras@@YA_KXZ ENDP	; ibmras::common::util::getMilliseconds
_TEXT	ENDS
EXTRN	__imp___time64:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
__Time$ = 8						; size = 4
_time	PROC
; File c:\program files (x86)\microsoft visual studio 10.0\vc\include\time.inl
; Line 132
	push	ebp
	mov	ebp, esp
; Line 133
	mov	eax, DWORD PTR __Time$[ebp]
	push	eax
	call	DWORD PTR __imp___time64
	add	esp, 4
; Line 134
	pop	ebp
	ret	0
_time	ENDP
_TEXT	ENDS
END
